# Generated by Django 4.2.6 on 2023-10-13 11:12

import base.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('contract_no', models.CharField(max_length=15, unique=True)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('state', models.CharField(max_length=30)),
                ('duty_station', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FlightBudget',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdvancedTravelPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=10)),
                ('year', models.CharField(default='2023', max_length=20, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('trip_plan', models.FileField(upload_to=base.models.get_upload_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
    ]
