# Generated by Django 4.2.6 on 2023-10-16 05:33

import base.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbudget',
            name='allocated_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flightbudget',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee'),
        ),
        migrations.AddField(
            model_name='flightbudget',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='flightbudget',
            name='remaining_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flightbudget',
            name='to_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='TravelBudget',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('remaining_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OPEBudget',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('remaining_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('ope_budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flight_budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flight_ticket', models.FileField(blank=True, upload_to=base.models.get_upload_path)),
                ('train_ticket', models.FileField(blank=True, upload_to=base.models.get_upload_path)),
                ('local_conveyance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
    ]
