# Generated by Django 4.2.6 on 2023-10-16 05:53

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_flightbudget_allocated_budget_flightbudget_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='flight_return_ticket',
            field=models.FileField(blank=True, upload_to=base.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='expense',
            name='place_of_visit',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='taxi_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='taxi_bill_proof',
            field=models.FileField(blank=True, upload_to=base.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='expense',
            name='train_return_ticket',
            field=models.FileField(blank=True, upload_to=base.models.get_upload_path),
        ),
    ]
