# Generated by Django 5.0.2 on 2024-06-19 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_expense_flight_return_ticket_expense_place_of_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='duty_station',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='DSA_Budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='DSA_Days_Budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='P_F_Budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='Terminal_Charges_Budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='Travel_Budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='Travel_Days_Budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profFee_monthly',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='programme',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_state', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='s_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_state', regex='^[a-zA-Z]+$')]),
        ),
    ]
