# Generated by Django 5.0.2 on 2024-06-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_employee_duty_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_no',
            field=models.IntegerField(),
        ),
    ]
